Repository Neogasogaeseo/Naega-Web, pull requests merged in 2022-10, with the labels that each got.

#418 MY 팀원소개서 이슈
  src/assets/icons/ic_arrow_detail.svg
  src/assets/icons/index.ts
  src/infrastructure/api/types/team.ts
  src/infrastructure/remote/user.ts
  src/presentation/components/FeedbackCard/Item/index.tsx
  src/presentation/components/FeedbackCard/Item/style.ts
  src/presentation/components/FeedbackCard/List/index.tsx
  src/presentation/pages/Home/MyPage/TeamPick/index.tsx
  src/presentation/pages/Home/Team/index.tsx
Labels: feature 🎄, layout 🍃

#419 너소서 팀에게 페이지 제거
  src/infrastructure/api/service-report.ts
  src/infrastructure/mock/service-report.ts
  src/infrastructure/remote/service-report.ts
  src/presentation/components/NeogaDetailFormCard/style.ts
  src/presentation/components/common/SelectBox/style.ts
  src/presentation/pages/Preferences/Feedback/index.tsx
  src/presentation/pages/Preferences/ServiceCenter/index.tsx
  src/presentation/pages/Preferences/index.tsx
  src/presentation/routes/PreferencesRouter.tsx
  src/presentation/routes/common/ErrorGuard.tsx
Labels: chore 🍣

#426 생성된 폼 이미지 저장 > (모바일) png에서 이미지 스타일 적용 안되는 버그 fix
  src/assets/images/img_character_logo.svg
  src/assets/images/img_empty_profile_small.svg
  src/assets/images/index.ts
  src/presentation/components/NeogaFormImageToSave/index.tsx
  src/presentation/components/NeogaFormImageToSave/style.ts
Labels: bug 🍄
