Repository Neogasogaeseo/Naega-Web, pull requests merged in 2022-07, with the labels that each got.

#374 QA 반영
  src/assets/images/index.ts
  src/infrastructure/remote/team.ts
  src/presentation/components/LoginForm/index.tsx
  src/presentation/components/LoginForm/style.ts
  src/presentation/components/common/BottomSheet/MyPageEdit/index.tsx
  src/presentation/pages/Home/MyPage/Keyword/index.tsx
  src/presentation/pages/Home/MyPage/index.tsx
  src/presentation/pages/Home/Neoga/index.tsx
  src/presentation/pages/Landing/index.tsx
  src/presentation/pages/Preferences/ServiceCenter/index.tsx
  src/presentation/pages/Team/Issue/NewIssue/style.ts
  src/presentation/pages/Team/Main/index.tsx
  src/presentation/routes/MyPageEditRouter.tsx
  src/presentation/routes/Router.tsx
  src/presentation/routes/UserRouter.tsx
  src/presentation/style/common/font-style.ts
  src/presentation/style/global/index.ts
Labels: fix ☔️, refactor 🪐, chore 🍣

#378 isHost 관련 작은 기능 추가 및 리팩토링
  src/infrastructure/api/types/team.ts
  src/infrastructure/remote/team.ts
  src/presentation/components/common/Modal/TeamLeave/index.tsx
  src/presentation/pages/Team/Main/index.tsx
  src/presentation/pages/Team/MemberManagement/index.tsx
Labels: refactor 🪐, chore 🍣

#383 7월 둘째주 자잘한 QA 반영
  src/assets/icons/ic_camera_main_coral.svg
  src/assets/icons/index.ts
  src/presentation/components/JoinForm/index.tsx
  src/presentation/components/NeososeoAnswerCard/Item/style.ts
  src/presentation/components/common/Modal/TeamLeave/index.tsx
  src/presentation/pages/Home/MyPage/style.ts
  src/presentation/pages/Team/Register/index.tsx
Labels: fix ☔️, chore 🍣
