Repository Neogasogaeseo/Naega-Web, pull requests merged in 2022-04, with the labels that each got.

#257 프로필 수정 페이지
  src/assets/icons/ic_crown.svg
  src/assets/icons/ic_edit.svg
  src/assets/icons/ic_edit_profile.svg
  src/assets/icons/ic_input_pencil.svg
  src/assets/icons/index.ts
  src/presentation/components/JoinForm/index.tsx
  src/presentation/components/common/BottomSheet/MyPageEdit/index.tsx
  src/presentation/components/common/BottomSheet/style.ts
  src/presentation/components/common/Input/index.tsx
  src/presentation/components/common/Navigation/style.ts
  src/presentation/pages/Edit/DeleteKeyword/index.tsx
  src/presentation/pages/Edit/DeleteKeyword/style.ts
  src/presentation/pages/Edit/Profile/index.tsx
  src/presentation/pages/Edit/Profile/style.ts
  src/presentation/pages/Home/MyPage/Keyword/index.tsx
  src/presentation/pages/Home/MyPage/Keyword/style.ts
  src/presentation/pages/Home/MyPage/index.tsx
  src/presentation/pages/Home/MyPage/style.ts
  src/presentation/pages/Team/Issue/Feedback/style.ts
  src/presentation/routes/MyPageEditRouter.tsx
  src/presentation/routes/Router.tsx
  src/presentation/routes/UserRouter.tsx
Labels: feature 🎄, layout 🍃

#248 링크 생성 페이지 스타일 수정
  src/assets/icons/ic_link_coral.svg
  src/assets/icons/ic_plus_coral.svg
  src/assets/icons/index.ts
  src/presentation/components/common/FormCard/style.ts
  src/presentation/pages/Neoga/Link/index.tsx
  src/presentation/pages/Neoga/Link/style.ts
Labels: layout 🍃

#254 팀 등록 시의 팀원 검색 뷰 response 수정 반영 및 엠티뷰 추가
  src/application/utils/constant.ts
  src/infrastructure/remote/login-user.ts
  src/infrastructure/remote/neoga.ts
  src/infrastructure/remote/neososeo-form.ts
  src/infrastructure/remote/team.ts
  src/infrastructure/remote/user.ts
  src/presentation/components/TeamMembers/index.tsx
  src/presentation/components/TeamMembers/style.ts
  src/presentation/components/common/Empty/UserSearch/index.tsx
  src/presentation/components/common/Empty/UserSearch/style.ts
Labels: layout 🍃, chore 🍣

#260 모달 공통 컴포넌트 만들고 적용해보기
  src/assets/icons/ic_warning.svg
  src/assets/icons/index.ts
  src/presentation/components/common/Modal/index.tsx
  src/presentation/components/common/Modal/style.ts
  src/presentation/components/common/ModalWrapper/index.tsx
  src/presentation/components/common/ModalWrapper/style.ts
  src/presentation/pages/Team/Edit/index.tsx
  src/presentation/pages/Team/Edit/style.ts
  src/presentation/pages/Team/Register/index.tsx
  src/presentation/pages/Team/Register/style.ts
  src/presentation/style/common/color.ts
  src/presentation/style/common/modal.ts
Labels: feature 🎄, layout 🍃

#261 팀 상세 페이지 바텀시트 추가, 팀원 목록 페이지 수정사항 반영
  src/assets/icons/ic_leave_team.svg
  src/assets/icons/ic_manage_team.svg
  src/assets/icons/index.ts
  src/presentation/components/common/BottomSheet/TeamMain/index.tsx
  src/presentation/components/common/BottomSheet/style.ts
  src/presentation/pages/Team/Main/index.tsx
  src/presentation/pages/Team/Member/index.tsx
  src/presentation/pages/Team/Member/style.ts
Labels: feature 🎄, layout 🍃

#265 너가소개서 설문 만들기 부분 디자인 수정사항 반영
  src/infrastructure/mock/neoga.data.ts
  src/presentation/components/NeogaCreateCard/Item/index.tsx
  src/presentation/components/NeogaMainCard/Item/index.tsx
  src/presentation/components/NeogaMainCard/Item/style.ts
Labels: layout 🍃

#256 알림창 API 연결과 뷰 짜기
  src/application/utils/date.ts
  src/infrastructure/api/team.ts
  src/infrastructure/api/types/team.ts
  src/infrastructure/mock/team.ts
  src/infrastructure/remote/base.ts
  src/infrastructure/remote/team.ts
  src/presentation/components/TeamNoticeItem/index.tsx
  src/presentation/components/TeamNoticeItem/style.ts
  src/presentation/components/common/Header/index.tsx
  src/presentation/pages/Team/Alert/index.tsx
  src/presentation/pages/Team/Alert/style.ts
  src/presentation/routes/TeamRouter.tsx
Labels: feature 🎄, layout 🍃

#270 ✨ feat: 팀원이 없는 팀은 피드백 작성을 막기
  src/assets/icons/ic_lock.svg
  src/assets/icons/index.ts
  src/assets/images/img_no_teammates.png
  src/assets/images/index.ts
  src/presentation/pages/Team/Issue/Feedback/index.tsx
  src/presentation/pages/Team/Issue/Feedback/style.ts
Labels: feature 🎄

#273 키워드 폰트 색상 추가
  src/infrastructure/api/types/user.ts
  src/infrastructure/mock/neoga.data.ts
  src/infrastructure/mock/team.data.ts
  src/infrastructure/mock/user.data.ts
  src/infrastructure/remote/neoga.ts
  src/infrastructure/remote/team.ts
  src/infrastructure/remote/user.ts
  src/presentation/components/TeamMembersSearchBar/index.tsx
  src/presentation/components/common/Keyword/Item/index.tsx
  src/presentation/components/common/Keyword/Item/style.ts
Labels: feature 🎄

#274 팀원 검색 뷰 리팩토링, 페이지네이션 적용하기
  src/App.tsx
  src/application/stores/team.ts
  src/application/utils/constant.ts
  src/infrastructure/api/team.ts
  src/infrastructure/api/types/team.ts
  src/infrastructure/remote/team.ts
  src/presentation/components/LandingPage/index.tsx
  src/presentation/components/SearchedUser/ForTeamRegister/index.tsx
  src/presentation/components/SearchedUser/ForTeamRegister/style.ts
  src/presentation/components/TeamMembers/index.tsx
  src/presentation/components/TeamMembers/style.ts
  src/presentation/components/TeamMembersSearchBar/index.tsx
  src/presentation/components/TeamMembersSearchBar/style.ts
  src/presentation/components/UserSearch/ForTeamRegister/Result/index.tsx
  src/presentation/components/UserSearch/ForTeamRegister/Result/style.ts
  src/presentation/components/UserSearch/ForTeamRegister/index.tsx
  src/presentation/components/UserSearch/ForTeamRegister/style.ts
  src/presentation/components/common/Empty/Feedback/index.tsx
  src/presentation/components/common/Empty/Feedback/style.ts
  src/presentation/components/common/ProfileItem/index.tsx
  src/presentation/pages/Home/Team/style.ts
  src/presentation/pages/Landing/index.tsx
  src/presentation/pages/Team/Register/index.tsx
Labels: refactor 🪐, feature 🎄

#275 너가소개서, 팀원소개서 픽하기 작업 일부
  src/assets/icons/ic_picked.svg
  src/assets/icons/ic_unpicked.svg
  src/assets/icons/index.ts
  src/infrastructure/remote/neoga.ts
  src/presentation/components/FeedbackCard/Item/index.tsx
  src/presentation/components/FeedbackCard/Item/style.ts
  src/presentation/components/NeososeoAnswerCard/Item/index.tsx
  src/presentation/components/NeososeoAnswerCard/Item/style.ts
  src/presentation/components/common/Empty/MyPick/index.tsx
  src/presentation/components/common/Empty/MyPick/style.ts
  src/presentation/pages/Home/MyPage/NeogaPick/index.tsx
  src/presentation/pages/Home/MyPage/NeogaPick/style.ts
  src/presentation/pages/Home/MyPage/TeamPick/index.tsx
  src/presentation/pages/Home/MyPage/TeamPick/style.ts
  src/presentation/pages/Home/MyPage/index.tsx
  src/presentation/pages/Home/MyPage/style.ts
  src/presentation/pages/Neoga/FormDetail/style.ts
  src/presentation/routes/UserRouter.tsx
Labels: feature 🎄, layout 🍃

#276 팀 수정하기, 삭제하기 API 연결하기
  src/infrastructure/api/index.ts
  src/infrastructure/api/team.ts
  src/infrastructure/api/types/errors.ts
  src/infrastructure/api/types/team.ts
  src/infrastructure/mock/team.ts
  src/infrastructure/remote/base.ts
  src/infrastructure/remote/team.ts
  src/presentation/pages/Team/Edit/index.tsx
Labels: feature 🎄
