Repository Neogasogaeseo/Naega-Web, pull requests merged in 2022-02, with the labels that each got.

#172 폰트 관련 멘토님 피드백 반영
  public/index.html
  src/assets/fonts/Pretendard-Bold.ttf
  src/assets/fonts/Pretendard-Bold.woff
  src/assets/fonts/Pretendard-Bold.woff2
  src/assets/fonts/Pretendard-Regular.ttf
  src/assets/fonts/Pretendard-Regular.woff
  src/assets/fonts/Pretendard-Regular.woff2
  src/assets/fonts/Pretendard-SemiBold.ttf
  src/assets/fonts/Pretendard-SemiBold.woff
  src/assets/fonts/Pretendard-SemiBold.woff2
  src/assets/fonts/font.css
  src/index.tsx
  src/presentation/style/global/index.ts
Labels: chore 🍣

#174 팀원 검색 뷰에서 Enter 키 입력 시 검색되도록 하기 (CommonInput 컴포넌트 수정)
  src/presentation/components/TeamMembersSearchBar/index.tsx
  src/presentation/components/common/CommonInput/index.tsx
  src/presentation/components/common/CommonInput/style.ts
  src/presentation/pages/Team/Issue/Keyword/index.tsx
  src/presentation/pages/Team/Register/Members/index.tsx
Labels: feature 🎄

#176 CommonInput ref 정말 필요한지 확인해보고 필요 없으면 없애기
  src/presentation/components/TeamMembersSearchBar/index.tsx
  src/presentation/components/common/CommonInput/index.tsx
  src/presentation/pages/Team/Register/index.tsx
Labels: chore 🍣

#178 너가소개서 결과 페이지 에러 해결
  src/infrastructure/remote/neoga-result.ts
  src/presentation/components/NeogaDetailForm/index.tsx
  src/presentation/components/NeogaDetailForm/style.ts
  src/presentation/components/common/Empty/MyPage/style.ts
  src/presentation/components/common/Toast/Item/style.ts
  src/presentation/components/common/Toast/List/style.ts
  src/presentation/pages/Home/Neoga/index.tsx
Labels: bug 🍄

#180 여러 페이지 보완
  src/assets/images/img_answer_done.svg
  src/assets/images/img_empty_feedback.svg
  src/assets/images/img_empty_form.svg
  src/assets/images/img_login_character.svg
  src/assets/images/index.ts
  src/infrastructure/remote/team.ts
  src/presentation/components/NeogaDetailForm/index.tsx
  src/presentation/components/NeogaDetailForm/style.ts
  src/presentation/components/TeamMembersSearchedUser/index.tsx
  src/presentation/components/common/Empty/Feedback/index.tsx
  src/presentation/components/common/Empty/Feedback/style.ts
  src/presentation/components/common/IssueMemberList/index.tsx
  src/presentation/components/common/NeogaResultCard/index.tsx
  src/presentation/components/common/ProfileItem/index.tsx
  src/presentation/pages/Home/MyPage/index.tsx
  src/presentation/pages/Home/Team/index.tsx
  src/presentation/pages/NeososeoForm/Answer/index.tsx
  src/presentation/pages/NeososeoForm/style.ts
  src/presentation/pages/Team/Issue/Feedback/index.tsx
  src/presentation/pages/Team/Issue/Feedback/style.ts
  src/presentation/pages/Team/Issue/Keyword/index.tsx
  src/presentation/pages/Team/Issue/NewIssue/index.tsx
  src/presentation/pages/Team/Issue/NewIssue/style.ts
  src/presentation/pages/Team/Issue/index.tsx
  src/presentation/pages/Team/Issue/style.ts
  src/presentation/pages/Team/Main/index.tsx
  src/presentation/pages/Team/Register/index.tsx
Labels: fix ☔️, refactor 🪐, chore 🍣

#186 랜딩 페이지 버그 없애기
  src/presentation/components/LandingPage/index.tsx
  src/presentation/pages/Landing/index.tsx
Labels: bug 🍄

#182 너소서 & 팀소서 메인 Can't perform a React state update on an unmounted component. 해결
  src/infrastructure/api/types/team.ts
  src/infrastructure/mock/team.data.ts
  src/infrastructure/remote/team.ts
  src/presentation/components/common/IssueCardList/index.tsx
  src/presentation/components/common/ProfileList/index.tsx
  src/presentation/pages/Home/MyPage/index.tsx
  src/presentation/pages/Home/Neoga/index.tsx
  src/presentation/pages/Home/Team/index.tsx
  src/presentation/pages/Neoga/Link/Result/index.tsx
  src/presentation/pages/NeososeoForm/Finish/index.tsx
  src/presentation/pages/Team/Main/index.tsx
  src/presentation/pages/Team/Register/index.tsx
Labels: bug 🍄, refactor 🪐

#190 console.log 숙청 및 e, err을 모두 error로 통합
  src/infrastructure/api/login-user.ts
  src/infrastructure/mock/neoga.ts
  src/infrastructure/mock/neososeo-form.ts
  src/infrastructure/remote/issue.ts
  src/infrastructure/remote/neoga.ts
  src/infrastructure/remote/team.ts
  src/presentation/components/JoinForm/index.tsx
  src/presentation/pages/Team/Issue/NewIssue/index.tsx
Labels: chore 🍣

#188 너소서 생성 첫화면 / 답변 첫화면 일그러진 UI 수정
  src/application/utils/string.ts
  src/presentation/components/common/NeososeoFormHeader/index.tsx
  src/presentation/components/common/Question/index.tsx
  src/presentation/components/common/Question/style.ts
Labels: fix ☔️, layout 🍃

#192 피드백과 이슈 등록 시 생기는 버그 없애기
  src/assets/icons/ic_dot.svg
  src/assets/icons/index.ts
  src/presentation/components/FeedbackCard/Item/index.tsx
  src/presentation/components/FeedbackCard/Item/style.ts
  src/presentation/components/NeogaDetailForm/Card/index.tsx
  src/presentation/components/NeogaDetailForm/style.ts
  src/presentation/pages/Team/Issue/Feedback/index.tsx
  src/presentation/pages/Team/Issue/NewIssue/index.tsx
Labels: bug 🍄

#193 FileUploader 버그 해결하기
  src/presentation/components/common/FileUpload/index.tsx
Labels: bug 🍄

#197 피드백 생성 이후 뒤로가기 스택에 쌓이는 오류 해결, 첫 피드백이 안 뜨는 오류 해결
  src/presentation/components/common/IssueCardList/index.tsx
  src/presentation/pages/Team/Issue/Feedback/index.tsx
  src/presentation/pages/Team/Issue/index.tsx
Labels: fix ☔️

#201 엠티뷰 방식 통일하기
  src/infrastructure/api/types/neoga.ts
  src/infrastructure/mock/neoga.data.ts
  src/infrastructure/remote/neoga-result.ts
  src/presentation/components/NeogaDetailForm/Card/index.tsx
  src/presentation/components/NeogaDetailForm/index.tsx
  src/presentation/components/NeogaDetailForm/style.ts
  src/presentation/components/common/Empty/HomeNeoga/index.tsx
  src/presentation/components/common/Empty/HomeNeoga/style.ts
  src/presentation/components/common/Empty/HomeTeam/index.tsx
  src/presentation/components/common/Empty/HomeTeam/style.ts
  src/presentation/components/common/Empty/NeogaDetailForm/index.tsx
  src/presentation/components/common/Empty/NeogaDetailForm/style.ts
  src/presentation/pages/Home/Neoga/index.tsx
  src/presentation/pages/Home/Neoga/styles.ts
  src/presentation/pages/Home/Team/index.tsx
  src/presentation/pages/Home/Team/style.ts
Labels: chore 🍣

#199 React Query 설치 및 팀소서 이슈 부분에 적용
  package.json
  src/App.tsx
  src/infrastructure/api/team.ts
  src/infrastructure/api/types/team.ts
  src/infrastructure/mock/team.data.ts
  src/infrastructure/mock/team.ts
  src/infrastructure/remote/issue.ts
  src/infrastructure/remote/team.ts
  src/presentation/pages/Team/Issue/NewIssue/index.tsx
  src/presentation/pages/Team/Issue/NewIssue/style.ts
  src/presentation/pages/Team/Main/index.tsx
  yarn.lock
Labels: fix ☔️, refactor 🪐
