Repository Neogasogaeseo/Naega-Web, pull requests merged in 2022-01, with the labels that each got.

#6 CI/CD 스크립트 작성
  .github/workflows/comment-pr.yml
  .github/workflows/deploy-dev.yml
  .github/workflows/deploy-feat.yml
  .github/workflows/lint.yml
  package.json
Labels: deployment 🐿, chore 🍣

#13 팀원소개서 관련 라우팅 및 페이지 컴포넌트 쓰기
  src/presentation/pages/Home/MyPage/index.tsx
  src/presentation/pages/Home/Neoga/index.tsx
  src/presentation/pages/Home/Team/index.tsx
  src/presentation/pages/Home/index.tsx
  src/presentation/pages/Team/Issue/Feedback/index.tsx
  src/presentation/pages/Team/Issue/Keyword/index.tsx
  src/presentation/pages/Team/Issue/index.tsx
  src/presentation/pages/Team/Main/index.tsx
  src/presentation/pages/Team/Register/Members/index.tsx
  src/presentation/pages/Team/Register/index.tsx
  src/presentation/routes/HomeRouter.tsx
  src/presentation/routes/Router.tsx
  src/presentation/routes/TeamRouter.tsx
  src/presentation/routes/UserRouter.tsx
Labels: feature 🎄

#15 color 상수 지정하기
  src/presentation/style/common/color.ts
Labels: chore 🍣

#17 버튼 스타일 상수 만들기
  src/presentation/style/common/button.ts
  tsconfig.paths.json
Labels: chore 🍣

#20 @style을 @styles로 변경
  src/presentation/style/common/button.ts
  tsconfig.paths.json
Labels: fix ☔️

#11 svg import 타입 수정
  src/assets/custom.d.ts
Labels: fix ☔️

#23 데이터 프로바이더 코드 짜기
  src/infrastructure/api/index.ts
  src/infrastructure/api/team.ts
  src/infrastructure/api/types/team.ts
  src/infrastructure/mock/team.data.ts
  src/infrastructure/mock/team.ts
  src/presentation/pages/Team/Issue/index.tsx
Labels: feature 🎄

#24 팀원소개서 메인 페이지 팀/팀원 목록
  src/App.tsx
  src/assets/icons/alertIcon.svg
  src/assets/icons/ic_plus.svg
  src/assets/icons/index.ts
  src/assets/images/img_empty_profile.svg
  src/assets/images/index.ts
  src/index.tsx
  src/presentation/components/ProfileList/index.tsx
  src/presentation/components/ProfileList/style.ts
  src/presentation/components/common/ProfileAddButton/index.tsx
  src/presentation/components/common/ProfileAddButton/style.ts
  src/presentation/components/common/ProfileItem/index.tsx
  src/presentation/components/common/ProfileItem/style.ts
  src/presentation/pages/Home/Team/index.tsx
  src/presentation/pages/Home/Team/style.ts
  src/presentation/pages/Team/Main/index.tsx
  src/presentation/style/common/button.ts
Labels: feature 🎄, layout 🍃

#22 StyledInput 컴포넌트 구현
  src/presentation/components/common/CommonInput/index.tsx
  src/presentation/components/common/CommonInput/style.ts
Labels: layout 🍃

#27 input 관련 공통 스타일 상수, 컴포넌트 만들기
  src/presentation/components/common/CommonInput/style.ts
  src/presentation/components/common/CommonLabel/index.tsx
  src/presentation/components/common/CommonLabel/style.ts
  src/presentation/style/common/input.ts
Labels: chore 🍣

#31 파일업로드 컴포넌트 구현
  src/assets/icons/ic_camera.svg
  src/assets/icons/index.ts
  src/presentation/components/common/FileUpload/index.tsx
  src/presentation/components/common/FileUpload/style.ts
Labels: feature 🎄, layout 🍃

#36 팀 등록하기 뷰 구현
  src/assets/images/img_team_add.svg
  src/assets/images/index.ts
  src/presentation/components/ProfileList/index.tsx
  src/presentation/components/common/CommonInput/index.tsx
  src/presentation/components/common/CommonLabel/index.tsx
  src/presentation/components/common/CommonLabel/style.ts
  src/presentation/pages/Team/Register/index.tsx
  src/presentation/pages/Team/Register/style.ts
  src/presentation/style/common/button.ts
Labels: feature 🎄, layout 🍃

#32 너가소개서/팀원소개서/마이페이지 Header
  src/assets/images/img_logo.svg
  src/assets/images/index.ts
  src/presentation/components/ProfileList/index.tsx
  src/presentation/components/ProfileList/style.ts
  src/presentation/components/common/Header/index.tsx
  src/presentation/components/common/Header/style.ts
  src/presentation/components/common/ProfileItem/index.tsx
  src/presentation/components/common/ProfileItem/style.ts
  src/presentation/pages/Home/Team/index.tsx
  src/presentation/pages/Home/Team/style.ts
  src/presentation/pages/Home/index.tsx
  src/presentation/pages/Home/style.ts
  src/presentation/style/global/index.ts
Labels: feature 🎄, layout 🍃

#43 너가소개서 만들기 화면 퍼블리싱
  src/infrastructure/api/index.ts
  src/infrastructure/api/neoga.ts
  src/infrastructure/api/types/neoga.ts
  src/infrastructure/mock/neoga.data.ts
  src/infrastructure/mock/neoga.ts
  src/presentation/components/NeogaCreateCard/Item/index.tsx
  src/presentation/components/NeogaCreateCard/Item/style.ts
  src/presentation/components/NeogaCreateCard/List/index.tsx
  src/presentation/components/NeogaCreateCard/List/style.ts
  src/presentation/components/common/HomeHeader/index.tsx
  src/presentation/components/common/HomeHeader/style.ts
  src/presentation/pages/Home/index.tsx
  src/presentation/pages/Neoga/Create/index.tsx
  src/presentation/pages/Neoga/Create/style.ts
  src/presentation/routes/NeogaRouter.tsx
  src/presentation/routes/Router.tsx
Labels: feature 🎄, layout 🍃

#45 팀원소개서 이슈생성하기/로그인,회원가입 구현
  .gitignore
  public/index.html
  src/assets/icons/ic_email.svg
  src/assets/icons/ic_kakao.svg
  src/assets/icons/index.ts
  src/assets/images/img_empty_join.svg
  src/assets/images/index.ts
  src/presentation/components/JoinForm/index.tsx
  src/presentation/components/JoinForm/style.ts
  src/presentation/components/LoginForm/OAuth.ts
  src/presentation/components/LoginForm/index.tsx
  src/presentation/components/LoginForm/style.ts
  src/presentation/components/common/CommonInput/index.tsx
  src/presentation/components/common/CommonInput/style.ts
  src/presentation/pages/Join/index.tsx
  src/presentation/pages/Login/index.tsx
  src/presentation/pages/Team/Issue/NewIssue/index.tsx
  src/presentation/pages/Team/Issue/NewIssue/style.ts
  src/presentation/routes/TeamRouter.tsx
Labels: feature 🎄, layout 🍃

#46 베이스 폰트 스타일 만들기
  src/presentation/style/common/font-style.ts
Labels: chore 🍣

#54 팀원 추가 뷰 퍼블리싱
  src/assets/icons/ic_back.svg
  src/assets/icons/ic_delete.svg
  src/assets/icons/ic_member_add.svg
  src/assets/icons/ic_search.svg
  src/assets/icons/index.ts
  src/infrastructure/api/types/team.ts
  src/infrastructure/api/types/user.ts
  src/infrastructure/mock/team.data.ts
  src/infrastructure/mock/user.data.ts
  src/presentation/components/ProfileList/index.tsx
  src/presentation/components/ProfileListSelectable/index.tsx
  src/presentation/components/TeamMembersSearchBar/index.tsx
  src/presentation/components/TeamMembersSearchBar/style.ts
  src/presentation/components/TeamMembersSearchResult/index.tsx
  src/presentation/components/TeamMembersSearchResult/style.ts
  src/presentation/components/common/Keyword/ImmutableList/index.tsx
  src/presentation/components/common/Keyword/Item/style.ts
  src/presentation/components/common/Keyword/MutableList/index.tsx
  src/presentation/components/common/ProfileItem/index.tsx
  src/presentation/pages/Home/Team/index.tsx
  src/presentation/pages/Team/Issue/Feedback/index.tsx
  src/presentation/pages/Team/Issue/Keyword/index.tsx
  src/presentation/pages/Team/Register/Members/index.tsx
  src/presentation/pages/Team/Register/Members/style.ts
  src/presentation/pages/Team/Register/index.tsx
  src/presentation/style/common/font-style.ts
  src/presentation/style/global/index.ts
Labels: layout 🍃

#55 팀 이슈 피드백 카드 컴포넌트 만들기 및 북마크 요청 목킹
  src/assets/icons/ic_bookmark_selected.svg
  src/assets/icons/ic_bookmark_unselected.svg
  src/assets/icons/ic_dot.svg
  src/assets/icons/index.ts
  src/infrastructure/api/team.ts
  src/infrastructure/api/types/team.ts
  src/infrastructure/mock/team.data.ts
  src/infrastructure/mock/team.ts
  src/presentation/components/IssueCard/index.tsx
  src/presentation/components/IssueCard/style.ts
  src/presentation/pages/Team/Issue/index.tsx
Labels: feature 🎄, layout 🍃

#57 🐛fix: 팀원 등록 뷰에서 아이콘이 잘리는 문제 해결
  src/assets/icons/ic_pencil.svg
  src/assets/icons/index.ts
  src/assets/images/img_team_add.svg
  src/presentation/pages/Team/Register/index.tsx
  src/presentation/pages/Team/Register/style.ts
  src/presentation/style/global/index.ts
Labels: fix ☔️

#59 MutableKeywordList에서 linear이 되어도 x가 잘 뜨게 하기
  src/assets/icons/ic_close_grey.svg
  src/assets/icons/ic_close_white.svg
  src/assets/icons/index.ts
  src/presentation/components/common/Keyword/ImmutableList/index.tsx
  src/presentation/components/common/Keyword/Item/index.tsx
  src/presentation/components/common/Keyword/Item/style.ts
  src/presentation/components/common/Keyword/MutableList/index.tsx
  src/presentation/components/common/Keyword/style.ts
Labels: layout 🍃

#51 팀원소개서 이슈 카드 리스트
  src/infrastructure/api/team.ts
  src/infrastructure/api/types/team.ts
  src/infrastructure/mock/team.data.ts
  src/infrastructure/mock/team.ts
  src/presentation/components/common/HomeHeader/index.tsx
  src/presentation/components/common/IssueCard/index.tsx
  src/presentation/components/common/IssueCard/style.ts
  src/presentation/components/common/IssueCardList/index.tsx
  src/presentation/components/common/IssueMemberList/index.tsx
  src/presentation/components/common/IssueMemberList/style.ts
  src/presentation/components/common/IssueTeamInfo/index.tsx
  src/presentation/components/common/IssueTeamInfo/style.ts
  src/presentation/pages/Home/Team/index.tsx
  src/presentation/pages/Team/Main/index.tsx
  src/presentation/pages/Team/Main/style.ts
Labels: feature 🎄, layout 🍃

#61 이슈 상단 첫페이지 구현
  src/infrastructure/mock/team.data.ts
  src/presentation/pages/Team/Issue/Feedback/style.ts
  src/presentation/pages/Team/Issue/index.tsx
  src/presentation/pages/Team/Issue/style.ts
  src/presentation/style/global/index.ts
Labels: layout 🍃

#64 #63번 버그 수정
  src/presentation/pages/Team/Issue/Keyword/index.tsx
  src/presentation/pages/Team/Issue/Keyword/style.ts
  src/presentation/style/common/animation.ts
Labels: fix ☔️

#72 팀원소개서 상세 페이지 팝업
  src/presentation/pages/Team/Main/MemberPopup/index.tsx
  src/presentation/pages/Team/Main/MemberPopup/style.ts
  src/presentation/pages/Team/Main/index.tsx
  src/presentation/pages/Team/Main/style.ts
Labels: layout 🍃

#65 팀원 추가 뷰 UI 기능 구현
  src/application/stores/team.ts
  src/assets/icons/ic_member_add.svg
  src/assets/icons/ic_member_added.svg
  src/assets/icons/index.ts
  src/infrastructure/api/types/team.ts
  src/presentation/components/TeamMembersSearchBar/index.tsx
  src/presentation/components/TeamMembersSearchResult/index.tsx
  src/presentation/components/TeamMembersSearchedMember/index.tsx
  src/presentation/components/TeamMembersSearchedMember/style.ts
  src/presentation/pages/Team/Register/Members/index.tsx
  src/presentation/pages/Team/Register/index.tsx
Labels: feature 🎄

#71 이슈 생성하기 기능 일부 수정
  src/presentation/pages/Team/Issue/NewIssue/index.tsx
  src/presentation/pages/Team/Issue/NewIssue/style.ts
Labels: fix ☔️, refactor 🪐

#78 베이스 토스트 굽기 (feat: recoil)
  src/App.tsx
  src/application/hooks/useToast.ts
  src/application/stores/toast.ts
  src/application/utils/etc.ts
  src/presentation/components/common/Toast/Item/index.tsx
  src/presentation/components/common/Toast/Item/style.ts
  src/presentation/components/common/Toast/List/index.tsx
  src/presentation/components/common/Toast/List/style.ts
  src/presentation/style/common/animation.ts
Labels: feature 🎄, layout 🍃

#75 1/14 UI 수정
  public/index.html
  src/infrastructure/api/user.ts
  src/infrastructure/mock/user.data.ts
  src/infrastructure/mock/user.ts
  src/presentation/components/common/CommonInput/index.tsx
  src/presentation/components/common/CommonInput/style.ts
  src/presentation/pages/Team/Issue/Feedback/index.tsx
  src/presentation/pages/Team/Issue/Keyword/index.tsx
  src/presentation/pages/Team/Issue/Keyword/style.ts
  src/presentation/style/global/index.ts
Labels: fix ☔️, layout 🍃

#82 너가소개서 만들기 페이지 퍼블리싱
  src/assets/icons/ic_arrow_right.svg
  src/assets/icons/index.ts
  src/infrastructure/api/neoga.ts
  src/infrastructure/api/types/neoga.ts
  src/infrastructure/mock/neoga.data.ts
  src/infrastructure/mock/neoga.ts
  src/presentation/components/NeogaCreateCard/Item/index.tsx
  src/presentation/components/NeogaCreateCard/Item/style.ts
  src/presentation/components/NeogaCreateCard/List/index.tsx
  src/presentation/components/NeogaCreateCard/List/style.ts
  src/presentation/pages/Neoga/Create/index.tsx
  src/presentation/pages/Neoga/Create/style.ts
Labels: feature 🎄, layout 🍃

#84 회원가입 정규식 적용 및 스타일 수정
  src/assets/icons/ic_profile.svg
  src/assets/icons/index.ts
  src/presentation/components/JoinForm/index.tsx
  src/presentation/components/JoinForm/style.ts
Labels: refactor 🪐, layout 🍃

#87 너소서 폼 작성 부분
  src/application/stores/neososeo-form.ts
  src/application/utils/string.ts
  src/assets/images/img_answerdone.svg
  src/assets/images/index.ts
  src/infrastructure/api/index.ts
  src/infrastructure/api/neososeo-form.ts
  src/infrastructure/api/types/neososeo-form.ts
  src/infrastructure/mock/neososeo-form.data.ts
  src/infrastructure/mock/neososeo-form.ts
  src/presentation/components/common/NeososeoFormHeader/index.tsx
  src/presentation/components/common/NeososeoFormHeader/style.ts
  src/presentation/pages/NeososeoForm/Answer/index.tsx
  src/presentation/pages/NeososeoForm/Answer/style.ts
  src/presentation/pages/NeososeoForm/Finish/index.tsx
  src/presentation/pages/NeososeoForm/Finish/style.ts
  src/presentation/pages/NeososeoForm/Home/index.tsx
  src/presentation/pages/NeososeoForm/Home/style.ts
  src/presentation/pages/NeososeoForm/Intro/index.tsx
  src/presentation/pages/NeososeoForm/index.tsx
  src/presentation/pages/NeososeoForm/style.ts
  src/presentation/pages/Team/Issue/Keyword/style.ts
  src/presentation/routes/FormRouter.tsx
  src/presentation/routes/HomeRouter.tsx
  src/presentation/routes/Router.tsx
Labels: feature 🎄, layout 🍃

#85 팀원소개서 메인, 상세 페이지 수정사항 반영
  src/assets/icons/ic_message.svg
  src/assets/icons/index.ts
  src/assets/images/img_empty_main.svg
  src/assets/images/index.ts
  src/infrastructure/api/team.ts
  src/infrastructure/api/types/team.ts
  src/infrastructure/mock/team.data.ts
  src/infrastructure/mock/team.ts
  src/presentation/components/common/HomeHeader/style.ts
  src/presentation/components/common/IssueCard/index.tsx
  src/presentation/components/common/IssueCardList/index.tsx
  src/presentation/components/common/IssueMemberList/index.tsx
  src/presentation/pages/Home/Team/Invitation/index.tsx
  src/presentation/pages/Home/Team/Invitation/style.ts
  src/presentation/pages/Home/Team/index.tsx
  src/presentation/pages/Home/Team/style.ts
  src/presentation/pages/Team/Issue/index.tsx
  src/presentation/pages/Team/Main/MemberPopup/index.tsx
  src/presentation/pages/Team/Main/MemberPopup/style.ts
  src/presentation/pages/Team/Main/index.tsx
  src/presentation/pages/Team/Main/style.ts
Labels: feature 🎄, layout 🍃

#89 링크 생성/링크 생성 완료/생성된 링크 뷰 퍼블리싱
  src/application/stores/team.ts
  src/application/utils/constant.ts
  src/assets/icons/ic_link_copy.svg
  src/assets/icons/index.ts
  src/assets/images/img_background_ellipse.svg
  src/assets/images/img_computer.svg
  src/assets/images/img_created_link.svg
  src/assets/images/img_new_link.svg
  src/assets/images/img_question_frame.svg
  src/assets/images/index.ts
  src/presentation/components/common/Question/index.tsx
  src/presentation/components/common/Question/style.ts
  src/presentation/pages/Neoga/Link/Created/index.tsx
  src/presentation/pages/Neoga/Link/New/index.tsx
  src/presentation/pages/Neoga/Link/index.tsx
  src/presentation/pages/Neoga/Link/style.ts
  src/presentation/routes/NeogaRouter.tsx
  src/presentation/style/common/font-style.ts
  src/presentation/style/common/input.ts
Labels: layout 🍃

#92 회원가입 완료페이지, 너가소개서 결과페이지 구현
  .vscode/settings.json
  src/assets/icons/ic_arrow_down.svg
  src/assets/icons/ic_arrow_up.svg
  src/assets/icons/ic_link.svg
  src/assets/icons/index.ts
  src/assets/images/img_empty_feedback.svg
  src/assets/images/img_party.svg
  src/assets/images/index.ts
  src/infrastructure/api/neoga.ts
  src/infrastructure/api/types/neoga.ts
  src/infrastructure/mock/neoga.data.ts
  src/infrastructure/mock/neoga.ts
  src/presentation/components/JoinCompleteForm/index.tsx
  src/presentation/components/JoinCompleteForm/style.ts
  src/presentation/components/JoinForm/index.tsx
  src/presentation/components/NeogaDetailForm/index.tsx
  src/presentation/components/NeogaDetailForm/style.ts
  src/presentation/pages/JoinComplete/index.tsx
  src/presentation/pages/Neoga/FormDetail/index.tsx
  src/presentation/routes/NeogaRouter.tsx
  src/presentation/routes/UserRouter.tsx
Labels: refactor 🪐, feature 🎄, layout 🍃

#96 팀멤버 타입 숙청
  src/application/stores/team.ts
  src/infrastructure/api/neoga.ts
  src/infrastructure/api/types/neoga.ts
  src/infrastructure/api/types/team.ts
  src/infrastructure/mock/team.data.ts
  src/presentation/components/NeogaDetailForm/index.tsx
  src/presentation/components/ProfileList/index.tsx
  src/presentation/components/ProfileListSelectable/index.tsx
  src/presentation/components/TeamMembersSearchBar/index.tsx
  src/presentation/components/TeamMembersSearchedMember/index.tsx
  src/presentation/components/common/IssueCard/index.tsx
  src/presentation/components/common/IssueCardList/index.tsx
  src/presentation/components/common/IssueMemberList/index.tsx
  src/presentation/components/common/Keyword/ImmutableList/index.tsx
  src/presentation/components/common/Keyword/Item/index.tsx
  src/presentation/components/common/Keyword/MutableList/index.tsx
  src/presentation/components/common/ProfileItem/index.tsx
  src/presentation/pages/Home/Team/index.tsx
  src/presentation/pages/JoinComplete/index.tsx
  src/presentation/pages/Neoga/FormDetail/index.tsx
  src/presentation/pages/Team/Issue/Feedback/index.tsx
  src/presentation/pages/Team/Issue/Keyword/index.tsx
  src/presentation/pages/Team/Main/MemberPopup/index.tsx
  src/presentation/pages/Team/Register/Members/index.tsx
Labels: fix ☔️, feature 🎄

#90 너소서 만들기 부분에 실서버 API 붙이기
  src/application/hooks/useLoginUser.ts
  src/infrastructure/api/index.ts
  src/infrastructure/api/login-user.ts
  src/infrastructure/api/types/neoga.ts
  src/infrastructure/api/user.ts
  src/infrastructure/mock/login-user.data.ts
  src/infrastructure/mock/login-user.ts
  src/infrastructure/mock/neoga.data.ts
  src/infrastructure/mock/user.data.ts
  src/infrastructure/mock/user.ts
  src/infrastructure/remote/base.ts
  src/infrastructure/remote/neoga.ts
Labels: feature 🎄

#101 팀원소개서 메인 페이지에 실서버 API 붙이기
  src/infrastructure/api/index.ts
  src/infrastructure/remote/base.ts
  src/infrastructure/remote/team.ts
  src/presentation/components/common/Toast/List/style.ts
  src/presentation/pages/Home/Team/Invitation/index.tsx
  src/presentation/pages/Home/Team/index.tsx
  tsconfig.paths.json
Labels: feature 🎄

#104 마이페이지 데이터 목킹 붙이기
  src/application/hooks/useLoginUser.ts
  src/application/stores/login-user.ts
  src/assets/icons/ic_arrow_view_all.svg
  src/assets/icons/ic_arrow_view_more.svg
  src/assets/icons/ic_arrow_view_more_close.svg
  src/assets/icons/ic_copy_mypage.svg
  src/assets/icons/ic_mypage_edit.svg
  src/assets/icons/index.ts
  src/infrastructure/api/neoga.ts
  src/infrastructure/api/types/team.ts
  src/infrastructure/api/types/user.ts
  src/infrastructure/api/user.ts
  src/infrastructure/mock/login-user.data.ts
  src/infrastructure/mock/neoga.ts
  src/infrastructure/mock/team.data.ts
  src/infrastructure/mock/user.data.ts
  src/infrastructure/mock/user.ts
  src/infrastructure/remote/neoga.ts
  src/presentation/components/FeedbackCard/ExpandableList/index.tsx
  src/presentation/components/FeedbackCard/Item/index.tsx
  src/presentation/components/FeedbackCard/Item/style.ts
  src/presentation/components/FeedbackCard/List/index.tsx
  src/presentation/components/FeedbackCard/List/style.ts
  src/presentation/components/NeososeoAnswerCard/ExpandableList/index.tsx
  src/presentation/components/NeososeoAnswerCard/Item/index.tsx
  src/presentation/components/NeososeoAnswerCard/Item/style.ts
  src/presentation/components/NeososeoAnswerCard/List/index.tsx
  src/presentation/components/ProfileList/index.tsx
  src/presentation/components/common/ExpandListButton/index.tsx
  src/presentation/components/common/ExpandListButton/style.ts
  src/presentation/components/common/HomeHeader/index.tsx
  src/presentation/components/common/HomeHeader/style.ts
  src/presentation/components/common/Toast/List/style.ts
  src/presentation/pages/Home/MyPage/index.tsx
  src/presentation/pages/Home/MyPage/style.ts
  src/presentation/pages/Team/Issue/index.tsx
  src/presentation/routes/HomeRouter.tsx
  src/presentation/style/common/font-style.ts
Labels: fix ☔️, feature 🎄

#112 카카오톡 소셜 로그인/ 회원가입 api 연결 완료!
  src/application/stores/kakao-auth.ts
  src/infrastructure/api/login-user.ts
  src/infrastructure/remote/base.ts
  src/presentation/components/JoinCompleteForm/index.tsx
  src/presentation/components/JoinForm/index.tsx
  src/presentation/components/LoginForm/OAuth.ts
  src/presentation/components/LoginForm/index.tsx
  src/presentation/components/LoginForm/style.ts
  src/presentation/pages/OAuthRedirectHandler/index.tsx
  src/presentation/routes/UserRouter.tsx
Labels: refactor 🪐, feature 🎄, layout 🍃

#115 로그인, 회원가입 이후 정보 저장 및 초기 입장 시 정보 저장 로직 추가
  src/application/hooks/useLoginUser.ts
  src/infrastructure/api/index.ts
  src/infrastructure/api/login-user.ts
  src/infrastructure/api/types/user.ts
  src/infrastructure/remote/login-user.ts
  src/infrastructure/remote/team.ts
  src/presentation/components/JoinForm/index.tsx
  src/presentation/components/common/ExpandListButton/index.tsx
  src/presentation/components/common/HomeHeader/index.tsx
  src/presentation/pages/Home/Team/index.tsx
  src/presentation/pages/OAuthRedirectHandler/index.tsx
Labels: feature 🎄

#114 팀원소개서 메인 일부, 상세 페이지 실서버 API 붙이기
  src/infrastructure/api/team.ts
  src/infrastructure/api/types/team.ts
  src/infrastructure/mock/team.data.ts
  src/infrastructure/mock/team.ts
  src/infrastructure/remote/team.ts
  src/presentation/pages/Home/Team/index.tsx
  src/presentation/pages/Team/Main/index.tsx
Labels: feature 🎄

#117 회원가입 완료페이지 연결 및 중복방지 구현
  src/infrastructure/api/login-user.ts
  src/infrastructure/api/team.ts
  src/presentation/components/JoinCompleteForm/index.tsx
  src/presentation/components/JoinForm/index.tsx
  src/presentation/pages/Team/Main/index.tsx
  src/presentation/routes/UserRouter.tsx
Labels: refactor 🪐, feature 🎄

#118 팀 이슈 피드백 데이터에 실서버 연결하기
  src/infrastructure/api/team.ts
  src/infrastructure/remote/team.ts
  src/presentation/components/common/IssueCardList/index.tsx
  src/presentation/pages/Team/Issue/Feedback/index.tsx
  src/presentation/pages/Team/Issue/index.tsx
Labels: feature 🎄

#116 private router 처리하기
  src/presentation/routes/HomeRouter.tsx
  src/presentation/routes/NeogaRouter.tsx
  src/presentation/routes/TeamRouter.tsx
  src/presentation/routes/UserRouter.tsx
  src/presentation/routes/common/PrivateRoute.tsx
Labels: feature 🎄

#119 너가소개서 메인, 폼(카드뷰 제외)
  src/assets/icons/ic_new_tag.svg
  src/assets/icons/ic_no_reply.svg
  src/assets/icons/ic_plus_mini.svg
  src/assets/icons/ic_whole.svg
  src/assets/icons/index.ts
  src/infrastructure/api/neoga.ts
  src/infrastructure/api/types/neoga.ts
  src/infrastructure/mock/neoga.data.ts
  src/infrastructure/mock/neoga.ts
  src/infrastructure/remote/neoga.ts
  src/presentation/components/NeogaMainCard/Item/index.tsx
  src/presentation/components/NeogaMainCard/Item/style.ts
  src/presentation/components/NeogaMainCard/List/index.tsx
  src/presentation/components/NeogaMainCard/List/style.ts
  src/presentation/components/common/NeogaResultCard/index.tsx
  src/presentation/components/common/NeogaResultCard/style.ts
  src/presentation/components/common/NeogaResultComment/index.tsx
  src/presentation/components/common/NeogaResultComment/style.ts
  src/presentation/components/common/ScrollToTop/index.tsx
  src/presentation/pages/Home/Neoga/index.tsx
  src/presentation/pages/Home/Neoga/styles.ts
  src/presentation/pages/Neoga/Result/index.tsx
  src/presentation/pages/Neoga/Result/style.ts
  src/presentation/pages/Team/Main/MemberPopup/index.tsx
  src/presentation/pages/Team/Main/MemberPopup/style.ts
  src/presentation/pages/Team/Main/index.tsx
  src/presentation/pages/Team/Main/style.ts
  src/presentation/routes/NeogaRouter.tsx
  src/presentation/routes/Router.tsx
Labels: feature 🎄, layout 🍃

#120 팀원 추가 뷰 api 연결 (유저 검색 결과 받아오기)
  src/application/stores/team.ts
  src/assets/icons/index.ts
  src/infrastructure/api/team.ts
  src/infrastructure/api/types/team.ts
  src/infrastructure/mock/team.ts
  src/infrastructure/remote/team.ts
  src/presentation/components/TeamMembersSearchBar/index.tsx
  src/presentation/components/TeamMembersSearchedMember/index.tsx
  src/presentation/components/TeamMembersSearchedUser/index.tsx
  src/presentation/components/TeamMembersSearchedUser/style.ts
  src/presentation/pages/Team/Register/Members/index.tsx
  src/presentation/pages/Team/Register/index.tsx
Labels: feature 🎄

#122 팀소서 이슈 피드백 나한테 달린거 북마크 기능 실서버 누나쿵
  src/infrastructure/api/types/team.ts
  src/infrastructure/remote/team.ts
  src/presentation/components/FeedbackCard/Item/index.tsx
Labels: feature 🎄

#125 랜딩페이지 구현하기
  package.json
  src/assets/images/img_glass.webp
  src/assets/images/img_landing_phone.svg
  src/assets/images/img_link.svg
  src/assets/images/img_main_character.svg
  src/assets/images/img_mypage.webp
  src/assets/images/img_teamsoseo.webp
  src/assets/images/index.ts
  src/assets/lottie/NeogaLottie/NeogaLandingLottie.json
  src/assets/lottie/NeogaLottie/index.tsx
  src/assets/lottie/TeamLottie/TeamLandingLottie.json
  src/assets/lottie/TeamLottie/index.tsx
  src/infrastructure/api/types/neoga.ts
  src/presentation/components/LandingPage/index.tsx
  src/presentation/components/LandingPage/style.ts
  src/presentation/pages/Landing/index.tsx
  src/presentation/routes/UserRouter.tsx
  yarn.lock
Labels: feature 🎄, layout 🍃

#128 팀원 추가 뷰 스타일 수정
  src/assets/icons/index.ts
  src/presentation/components/TeamMembersSearchBar/index.tsx
  src/presentation/components/TeamMembersSearchBar/style.ts
  src/presentation/components/common/CommonInput/index.tsx
  src/presentation/components/common/CommonInput/style.ts
  src/presentation/components/common/Keyword/Item/index.tsx
  src/presentation/components/common/Keyword/Item/style.ts
  src/presentation/pages/Team/Register/Members/index.tsx
Labels: feature 🎄, layout 🍃

#134 겟 폼 인포, 포스트 폼 누나쿵
  src/infrastructure/api/index.ts
  src/infrastructure/api/neososeo-form.ts
  src/infrastructure/mock/neososeo-form.ts
  src/infrastructure/remote/neososeo-form.ts
  src/infrastructure/remote/user.ts
  src/presentation/components/common/Keyword/ImmutableList/index.tsx
  src/presentation/components/common/Question/index.tsx
  src/presentation/components/common/Question/style.ts
  src/presentation/pages/NeososeoForm/Answer/index.tsx
  src/presentation/pages/NeososeoForm/Home/index.tsx
  src/presentation/pages/NeososeoForm/Home/style.ts
  src/presentation/pages/NeososeoForm/Intro/index.tsx
  src/presentation/pages/NeososeoForm/index.tsx
  src/presentation/pages/Team/Issue/Keyword/index.tsx
  src/presentation/routes/Router.tsx
Labels: feature 🎄

#137 이슈생성하기 서버 api POST 요청 보내기
  src/infrastructure/api/types/team.ts
  src/infrastructure/remote/issue.ts
  src/presentation/pages/Team/Issue/NewIssue/index.tsx
Labels: refactor 🪐, feature 🎄

#139 너가소개서 카드뷰 실서버 api 연결
  src/infrastructure/api/neoga.ts
  src/infrastructure/api/types/neoga.ts
  src/infrastructure/mock/neoga.data.ts
  src/infrastructure/mock/neoga.ts
  src/infrastructure/remote/neoga.ts
  src/infrastructure/remote/team.ts
  src/presentation/components/NeogaMainCard/Item/style.ts
  src/presentation/components/common/NeogaResultCard/index.tsx
  src/presentation/components/common/NeogaResultCard/style.ts
  src/presentation/components/common/NeogaResultComment/index.tsx
  src/presentation/components/common/NeogaResultComment/style.ts
  src/presentation/pages/Home/Neoga/index.tsx
  src/presentation/pages/Neoga/Result/index.tsx
  src/presentation/pages/Team/Main/index.tsx
Labels: feature 🎄

#145 너가소개서 결과페이지 서버 연결
  src/infrastructure/api/types/neoga.ts
  src/infrastructure/api/types/team.ts
  src/infrastructure/mock/neoga.ts
  src/infrastructure/remote/neoga-result.ts
  src/infrastructure/remote/neoga.ts
  src/infrastructure/remote/team.ts
  src/presentation/components/NeogaDetailForm/index.tsx
  src/presentation/components/NeogaDetailForm/style.ts
  src/presentation/pages/Neoga/FormDetail/index.tsx
  src/presentation/pages/Neoga/Result/index.tsx
Labels: feature 🎄

#141 링크 생성 뷰 너소서 정보 get 누나쿵
  src/infrastructure/api/neoga.ts
  src/infrastructure/api/types/neoga.ts
  src/infrastructure/mock/neoga.ts
  src/infrastructure/remote/neoga.ts
  src/presentation/pages/Neoga/Link/index.tsx
Labels: feature 🎄

#146 링크 생성하기 뷰 링크 생성 post 누나쿵
  src/application/utils/copyClipboard.ts
  src/infrastructure/api/neoga.ts
  src/infrastructure/mock/neoga.ts
  src/infrastructure/remote/neoga.ts
  src/presentation/pages/Neoga/Link/Result/index.tsx
Labels: feature 🎄

#148 레이지로딩 적용
  src/presentation/routes/FormRouter.tsx
  src/presentation/routes/HomeRouter.tsx
  src/presentation/routes/NeogaRouter.tsx
  src/presentation/routes/Router.tsx
  src/presentation/routes/TeamRouter.tsx
  src/presentation/routes/UserRouter.tsx
Labels: chore 🍣

#150 카카오 로그인 redirect uri 변경
  src/application/utils/constant.ts
  src/presentation/components/LoginForm/OAuth.ts
  src/presentation/components/NeogaDetailForm/index.tsx
  src/presentation/pages/Neoga/Link/Result/index.tsx
Labels: feature 🎄

#151 스타일 전체 수정
  src/presentation/components/FeedbackCard/Item/style.ts
  src/presentation/components/JoinCompleteForm/index.tsx
  src/presentation/components/JoinCompleteForm/style.ts
  src/presentation/components/JoinForm/style.ts
  src/presentation/components/LoginForm/style.ts
  src/presentation/components/NeogaMainCard/List/style.ts
  src/presentation/components/NeososeoAnswerCard/Item/style.ts
  src/presentation/components/common/HomeHeader/style.ts
  src/presentation/components/common/NeososeoFormHeader/style.ts
  src/presentation/components/common/Question/style.ts
  src/presentation/components/common/Toast/Item/style.ts
  src/presentation/pages/Home/MyPage/index.tsx
  src/presentation/pages/Home/MyPage/style.ts
  src/presentation/pages/Home/Neoga/styles.ts
  src/presentation/pages/Home/Team/Invitation/style.ts
  src/presentation/pages/Home/Team/style.ts
  src/presentation/pages/Home/style.ts
  src/presentation/pages/Neoga/Create/index.tsx
  src/presentation/pages/Neoga/Create/style.ts
  src/presentation/pages/Neoga/Link/Result/style.ts
  src/presentation/pages/Neoga/Link/style.ts
  src/presentation/pages/Neoga/Result/style.ts
  src/presentation/pages/NeososeoForm/Finish/style.ts
  src/presentation/pages/NeososeoForm/Home/style.ts
  src/presentation/pages/NeososeoForm/style.ts
  src/presentation/pages/Team/Issue/Feedback/style.ts
  src/presentation/pages/Team/Issue/Keyword/style.ts
  src/presentation/pages/Team/Issue/NewIssue/index.tsx
  src/presentation/pages/Team/Issue/NewIssue/style.ts
  src/presentation/pages/Team/Issue/style.ts
  src/presentation/pages/Team/Main/style.ts
  src/presentation/pages/Team/Register/Members/style.ts
  src/presentation/pages/Team/Register/style.ts
  src/presentation/style/global/index.ts
Labels: layout 🍃

#152 마이페이지 끝장내기
  src/assets/icons/ic_empty_feedback.svg
  src/assets/icons/index.ts
  src/infrastructure/remote/user.ts
  src/presentation/components/common/Empty/MyPage/index.tsx
  src/presentation/components/common/Empty/MyPage/style.ts
  src/presentation/pages/Home/MyPage/index.tsx
  src/presentation/style/common/font-style.ts
Labels: feature 🎄

#153 랜딩페이지 리펙토링
  src/assets/images/img_mypage.svg
  src/assets/images/img_mypage.webp
  src/assets/images/index.ts
  src/assets/lottie/NeogaLottie/index.tsx
  src/assets/lottie/TeamLottie/index.tsx
  src/presentation/components/LandingPage/index.tsx
  src/presentation/components/LandingPage/style.ts
  src/presentation/components/NeogaDetailForm/style.ts
Labels: fix ☔️, refactor 🪐

#157 keyword empty view 더하기
  src/assets/icons/ic_empty_keyword.svg
  src/assets/icons/index.ts
  src/infrastructure/remote/team.ts
  src/presentation/components/common/Empty/Keyword/index.tsx
  src/presentation/components/common/Empty/Keyword/style.ts
  src/presentation/pages/NeososeoForm/Intro/index.tsx
  src/presentation/pages/Team/Issue/Keyword/index.tsx
  src/presentation/style/common/font-style.ts
Labels: fix ☔️, feature 🎄, layout 🍃

#158 링크 공유하기 관련 메타 태그 설정
  public/index.html
  src/assets/images/img_thumbnail.png
  src/infrastructure/api/types/neoga.ts
  src/infrastructure/mock/neoga.data.ts
  src/infrastructure/remote/neoga.ts
  src/presentation/components/common/NeogaResultComment/index.tsx
  src/presentation/pages/Home/Neoga/index.tsx
  src/presentation/pages/Neoga/Result/index.tsx
Labels: chore 🍣

#161 자잘한 스타일 수정
  src/presentation/components/TeamMembersSearchBar/index.tsx
  src/presentation/components/common/CommonInput/index.tsx
  src/presentation/pages/NeososeoForm/style.ts
  src/presentation/pages/Team/Register/Members/index.tsx
  src/presentation/pages/Team/Register/index.tsx
Labels: layout 🍃

#163 너가소개서 생성 시 생기던 오류 다 수정
  src/infrastructure/api/neoga.ts
  src/infrastructure/mock/neoga.ts
  src/infrastructure/remote/neoga.ts
  src/infrastructure/remote/user.ts
  src/presentation/pages/Home/Neoga/index.tsx
  src/presentation/pages/Neoga/Link/Result/index.tsx
Labels: fix ☔️

#164 너소서 피드백 put API 붙이기
  src/infrastructure/api/types/neoga.ts
  src/infrastructure/remote/neoga.ts
  src/presentation/components/NeogaDetailForm/Card/index.tsx
  src/presentation/components/NeogaDetailForm/index.tsx
  src/presentation/components/NeogaDetailForm/style.ts
  src/presentation/pages/Home/MyPage/index.tsx
Labels: fix ☔️, feature 🎄

#167 이미지 리사이징 유틸 만들기
  src/application/utils/browser.ts
  src/application/utils/image.ts
  src/presentation/components/common/FileUpload/index.tsx
Labels: feature 🎄

#168 google analytics 추가
  package.json
  public/index.html
  src/App.tsx
  src/application/hooks/useGoogleAnalytics.ts
  yarn.lock
Labels: deployment 🐿

#171 노션에 정리해둔 리팩토링 항목 일부 반영
  src/infrastructure/api/types/team.ts
  src/infrastructure/remote/team.ts
  src/presentation/components/FeedbackCard/List/index.tsx
  src/presentation/components/JoinCompleteForm/index.tsx
  src/presentation/components/JoinCompleteForm/style.ts
  src/presentation/components/LandingPage/index.tsx
  src/presentation/components/LoginForm/index.tsx
  src/presentation/components/NeogaCreateCard/Item/style.ts
  src/presentation/components/NeogaDetailForm/style.ts
  src/presentation/components/NeososeoAnswerCard/Item/style.ts
  src/presentation/components/NeososeoAnswerCard/List/index.tsx
  src/presentation/components/ProfileListSelectable/index.tsx
  src/presentation/components/TeamMembersSearchedUser/index.tsx
  src/presentation/components/TeamMembersSearchedUser/style.ts
  src/presentation/components/common/Empty/MyPage/index.tsx
  src/presentation/components/common/HomeHeader/index.tsx
  src/presentation/components/common/NeososeoFormHeader/index.tsx
  src/presentation/components/common/ProfileAddButton/index.tsx
  src/presentation/components/common/ProfileList/index.tsx
  src/presentation/components/common/ProfileList/style.ts
  src/presentation/pages/Home/MyPage/index.tsx
  src/presentation/pages/Home/MyPage/style.ts
  src/presentation/pages/Home/Team/index.tsx
  src/presentation/pages/Neoga/Create/index.tsx
  src/presentation/pages/Neoga/Create/style.ts
  src/presentation/pages/Neoga/Result/index.tsx
  src/presentation/pages/Team/Issue/index.tsx
  src/presentation/pages/Team/Issue/style.ts
  src/presentation/pages/Team/Main/index.tsx
  src/presentation/pages/Team/Register/Members/style.ts
  src/presentation/pages/Team/Register/index.tsx
Labels: bug 🍄, refactor 🪐
