Repository Neogasogaeseo/Naega-Web, pull requests merged in 2022-08, with the labels that each got.

#382 픽하기 리팩토링 + 요청 이루어지는 동안 재요청 못하도록 막기
  src/application/hooks/queries/team.ts
  src/application/hooks/queries/user.ts
  src/infrastructure/api/team.ts
  src/infrastructure/remote/team.ts
  src/presentation/components/FeedbackCard/Item/index.tsx
  src/presentation/components/FeedbackCard/List/index.tsx
  src/presentation/components/NeososeoAnswerCard/Item/index.tsx
  src/presentation/components/NeososeoAnswerCard/List/index.tsx
  src/presentation/components/common/BottomSheet/NeososeoPicker/index.tsx
  src/presentation/components/common/BottomSheet/TeamsoseoPicker/index.tsx
  src/presentation/components/common/Modal/TeamLeave/index.tsx
  src/presentation/pages/Home/MyPage/NeogaPick/index.tsx
  src/presentation/pages/Home/MyPage/TeamPick/index.tsx
  src/presentation/pages/Neoga/FormDetail/index.tsx
  src/presentation/pages/Team/Edit/index.tsx
  tsconfig.paths.json
Labels: refactor 🪐, chore 🍣

#393 마이페이지 관련 QA 반영
  src/application/utils/string.ts
  src/infrastructure/api/types/user.ts
  src/infrastructure/mock/user.data.ts
  src/infrastructure/remote/neoga.ts
  src/infrastructure/remote/neososeo-form.ts
  src/infrastructure/remote/user.ts
  src/presentation/components/MyItem/index.tsx
  src/presentation/components/MyItem/style.ts
  src/presentation/components/MySelectableList/index.tsx
  src/presentation/components/MySelectableList/style.ts
  src/presentation/components/common/ProfileList/style.ts
  src/presentation/pages/Home/MyPage/NeogaPick/index.tsx
  src/presentation/pages/Home/MyPage/NeogaPick/style.ts
  src/presentation/pages/Home/MyPage/TeamPick/index.tsx
  src/presentation/pages/Home/MyPage/TeamPick/style.ts
  src/presentation/pages/Home/MyPage/index.tsx
Labels: fix ☔️, chore 🍣

#386 7월 다섯째 주 QA 반영 작업
  src/presentation/components/JoinForm/index.tsx
  src/presentation/components/JoinForm/style.ts
  src/presentation/components/common/ImageUpload/index.tsx
  src/presentation/components/common/ImageUpload/style.ts
  src/presentation/pages/Preferences/ServiceCenter/index.tsx
  src/presentation/pages/Team/Issue/NewIssue/index.tsx
  src/presentation/pages/Team/Issue/NewIssue/style.ts
  src/presentation/pages/Team/Register/index.tsx
Labels: fix ☔️

#387 자잘한 수정사항 반영
  src/infrastructure/api/service-report.ts
  src/infrastructure/remote/service-report.ts
  src/presentation/components/FeedbackCard/Item/style.ts
  src/presentation/components/JoinCompleteForm/index.tsx
  src/presentation/components/NeogaCreateCard/List/index.tsx
  src/presentation/components/common/Header/index.tsx
  src/presentation/components/common/ImageUpload/index.tsx
  src/presentation/pages/Home/Neoga/index.tsx
  src/presentation/pages/Home/Team/index.tsx
  src/presentation/pages/Neoga/FormDetail/index.tsx
  src/presentation/pages/Preferences/ServiceCenter/index.tsx
  src/presentation/pages/Team/Issue/Edit/index.tsx
  src/presentation/pages/Team/Issue/NewIssue/index.tsx
  src/presentation/pages/Team/Issue/style.ts
  src/presentation/pages/Team/Main/index.tsx
  src/presentation/pages/Team/MemberManagement/index.tsx
Labels: chore 🍣

#395 기획 수정사항 반영
  src/assets/icons/ic_warning_coral.svg
  src/assets/icons/index.ts
  src/presentation/components/MySelectableList/style.ts
  src/presentation/components/common/Modal/index.tsx
  src/presentation/components/common/Modal/style.ts
  src/presentation/pages/Preferences/Feedback/index.tsx
  src/presentation/pages/Preferences/index.tsx
  src/presentation/pages/Team/Issue/Feedback/style.ts
  src/presentation/routes/common/ErrorGuard.tsx
  src/presentation/style/common/modal.ts
Labels: chore 🍣
