Repository Neogasogaeseo/Naega-Web, pull requests merged in 2022-06, with the labels that each got.

#352 QA 반영
  src/assets/icons/ic_paper_airplane.svg
  src/assets/icons/index.ts
  src/infrastructure/api/types/errors.ts
  src/infrastructure/remote/neoga.ts
  src/presentation/components/common/ImageUpload/index.tsx
  src/presentation/components/common/ImageUpload/style.ts
  src/presentation/pages/MyProfileEdit/index.tsx
  src/presentation/pages/MyProfileEdit/style.ts
  src/presentation/pages/Team/Edit/index.tsx
  src/presentation/pages/Team/Edit/style.ts
  src/presentation/routes/common/ErrorGuard.tsx
Labels: fix ☔️, layout 🍃, chore 🍣

#355 QA 잔잔바리 반영
  src/presentation/pages/Home/MyPage/index.tsx
  src/presentation/pages/NeososeoForm/Answer/index.tsx
  src/presentation/pages/Team/Issue/Feedback/index.tsx
Labels: fix ☔️

#354 팀 나가기 1인팀 아닌데 1인팀으로 인식하는 버그 해결
  src/presentation/components/common/Modal/TeamLeave/index.tsx
Labels: fix ☔️

#367 QA 반영
  src/infrastructure/api/types/errors.ts
  src/infrastructure/remote/user.ts
  src/presentation/components/FeedbackCard/Item/index.tsx
  src/presentation/components/common/Empty/Feedback/index.tsx
  src/presentation/components/common/Empty/Feedback/style.ts
  src/presentation/components/common/FormCard/index.tsx
  src/presentation/components/common/SelectBox/index.tsx
  src/presentation/components/common/SelectBox/style.ts
  src/presentation/pages/Home/MyPage/style.ts
  src/presentation/pages/MyProfileEdit/index.tsx
  src/presentation/pages/Team/Issue/index.tsx
  src/presentation/pages/Team/Issue/style.ts
  src/presentation/routes/common/ErrorGuard.tsx
Labels: fix ☔️, chore 🍣

#369 방금 생성한 키워드를 삭제한 경우 키워드를 삭제하는 api 호출
  src/infrastructure/api/user.ts
  src/infrastructure/mock/user.ts
  src/infrastructure/remote/user.ts
  src/presentation/pages/Team/Issue/Keyword/index.tsx
Labels: bug 🍄, feature 🎄

#370 자잘한 QA 반영
  src/presentation/components/common/BottomSheet/index.tsx
  src/presentation/components/common/BottomSheet/style.ts
  src/presentation/components/common/Modal/TeamLeave/index.tsx
  src/presentation/pages/Preferences/ServiceCenter/index.tsx
  src/presentation/pages/Team/Issue/Edit/index.tsx
  src/presentation/pages/Team/Issue/Edit/style.ts
  src/presentation/pages/Team/Issue/NewIssue/index.tsx
  src/presentation/pages/Team/Issue/NewIssue/style.ts
Labels: fix ☔️, chore 🍣
