Repository Neogasogaeseo/Naega-Web, pull requests merged in 2022-05, with the labels that each got.

#277 프로필 수정 페이지 API 연결
  src/infrastructure/api/types/user.ts
  src/infrastructure/api/user.ts
  src/infrastructure/mock/user.data.ts
  src/infrastructure/mock/user.ts
  src/infrastructure/remote/user.ts
  src/presentation/components/common/Input/index.tsx
  src/presentation/pages/Edit/Profile/index.tsx
Labels: feature 🎄

#279 기획, 디자인 수정사항 반영 및 리팩토링
  src/assets/icons/ic_no_reply.svg
  src/assets/icons/index.ts
  src/infrastructure/api/neoga.ts
  src/infrastructure/api/types/neoga.ts
  src/infrastructure/api/types/user.ts
  src/infrastructure/mock/neoga.data.ts
  src/infrastructure/mock/neoga.ts
  src/infrastructure/mock/user.data.ts
  src/infrastructure/remote/neoga.ts
  src/infrastructure/remote/neososeo-form.ts
  src/infrastructure/remote/user.ts
  src/presentation/components/NeogaCreateCard/Item/index.tsx
  src/presentation/components/common/BottomSheet/MyPageEdit/index.tsx
  src/presentation/components/common/NeogaResultCard/index.tsx
  src/presentation/components/common/NeogaResultCard/style.ts
  src/presentation/pages/Home/MyPage/index.tsx
  src/presentation/pages/Neoga/Result/index.tsx
Labels: refactor 🪐, feature 🎄, layout 🍃

#283 헤더 알림 api remote로 변경
  src/infrastructure/api/header.ts
  src/infrastructure/api/index.ts
  src/infrastructure/remote/header.ts
  src/presentation/components/common/Header/index.tsx
Labels: feature 🎄

#280 팀소서 이슈 페이지 서버 반영 및 디자인 수정
  src/application/stores/team.ts
  src/infrastructure/api/team.ts
  src/infrastructure/api/types/team.ts
  src/infrastructure/mock/team.data.ts
  src/infrastructure/mock/team.ts
  src/infrastructure/remote/neoga.ts
  src/infrastructure/remote/team.ts
  src/presentation/components/FeedbackCard/Item/index.tsx
  src/presentation/components/FeedbackCard/Item/style.ts
  src/presentation/components/FeedbackCard/List/index.tsx
  src/presentation/components/common/BottomSheet/TeamsoseoPicker/index.tsx
  src/presentation/components/common/Modal/DeleteFeedback/index.tsx
  src/presentation/components/common/Modal/DeleteIssue/index.tsx
  src/presentation/pages/Team/Issue/Feedback/index.tsx
  src/presentation/pages/Team/Issue/index.tsx
  src/presentation/pages/Team/Issue/style.ts
Labels: feature 🎄

#287 너소서 폼 답변 조회 디자인 반영, 너소서 폼 답변 삭제 서버 연결
  src/assets/images/img_empty_form.svg
  src/assets/images/index.ts
  src/infrastructure/remote/neoga.ts
  src/presentation/components/NeogaDetailFormCard/index.tsx
  src/presentation/components/NeogaDetailFormCard/style.ts
  src/presentation/components/common/Empty/NeogaDetailForm/index.tsx
  src/presentation/components/common/Empty/NeogaDetailForm/style.ts
  src/presentation/pages/Neoga/FormDetail/index.tsx
  src/presentation/pages/Neoga/FormDetail/style.ts
Labels: feature 🎄

#288 너소서 폼 작성 정보 조회 서버 리스폰스 수정 및 뷰에 반영
  src/infrastructure/api/types/neososeo-form.ts
  src/infrastructure/mock/neososeo-form.data.ts
  src/infrastructure/remote/neososeo-form.ts
  src/presentation/components/common/Header/index.tsx
  src/presentation/pages/NeososeoForm/Home/index.tsx
Labels: feature 🎄

#296 팀 등록하기 페이지 뒤로가기 버튼 안눌리던 오류 해결
  src/presentation/pages/Team/Register/index.tsx
  src/presentation/pages/Team/Register/style.ts
Labels: fix ☔️

#293 팀원 관리하기 페이지
  src/infrastructure/api/team.ts
  src/infrastructure/api/types/team.ts
  src/infrastructure/mock/team.ts
  src/infrastructure/remote/team.ts
  src/presentation/components/common/BottomSheet/TeamMain/index.tsx
  src/presentation/components/common/Navigation/index.tsx
  src/presentation/pages/Team/MemberManagement/index.tsx
  src/presentation/pages/Team/MemberManagement/style.ts
  src/presentation/routes/TeamRouter.tsx
Labels: feature 🎄, layout 🍃

#299 My 키워드 페이지 API 연결
  src/infrastructure/api/types/user.ts
  src/infrastructure/api/user.ts
  src/infrastructure/mock/user.data.ts
  src/infrastructure/mock/user.ts
  src/infrastructure/remote/user.ts
  src/presentation/components/common/BottomSheet/MyPageEdit/index.tsx
  src/presentation/components/common/Keyword/ImmutableList/index.tsx
  src/presentation/components/common/Keyword/Item/index.tsx
  src/presentation/components/common/Keyword/Item/style.ts
  src/presentation/components/common/Keyword/MutableList/index.tsx
  src/presentation/pages/Edit/DeleteKeyword/index.tsx
  src/presentation/pages/Edit/DeleteKeyword/style.ts
  src/presentation/pages/Home/MyPage/Keyword/index.tsx
  src/presentation/pages/Home/MyPage/Keyword/style.ts
  src/presentation/routes/MyPageEditRouter.tsx
Labels: feature 🎄

#295 마이페이지 서버 리스폰스 반영, 디자인 반영, UX라이팅 수정
  src/application/utils/etc.ts
  src/infrastructure/remote/user.ts
  src/presentation/components/common/Empty/MyPage/index.tsx
  src/presentation/components/common/Empty/MyPage/style.ts
  src/presentation/components/common/Header/index.tsx
  src/presentation/components/common/Header/style.ts
  src/presentation/components/common/HomeHeader/index.tsx
  src/presentation/pages/Home/MyPage/index.tsx
  src/presentation/pages/Home/MyPage/style.ts
Labels: fix ☔️

#301 스켈레톤 UI 적용하기
  src/presentation/components/common/Skeleton/CardItem/index.tsx
  src/presentation/components/common/Skeleton/CardItem/style.ts
  src/presentation/components/common/Skeleton/MyPageInfo/index.tsx
  src/presentation/components/common/Skeleton/MyPageInfo/style.ts
  src/presentation/components/common/Skeleton/NSSPick/index.tsx
  src/presentation/components/common/Skeleton/NSSPick/style.ts
  src/presentation/components/common/Skeleton/TSSPick/index.tsx
  src/presentation/components/common/Skeleton/TSSPick/style.ts
  src/presentation/components/common/Skeleton/TeamIssue/index.tsx
  src/presentation/components/common/Skeleton/TeamIssue/style.ts
  src/presentation/components/common/Skeleton/TeamProfile/index.tsx
  src/presentation/components/common/Skeleton/TeamProfile/style.ts
  src/presentation/components/common/Skeleton/TemplateList/index.tsx
  src/presentation/components/common/Skeleton/TemplateList/style.ts
  src/presentation/components/common/Skeleton/style.ts
  src/presentation/pages/Home/MyPage/index.tsx
  src/presentation/pages/Home/Neoga/index.tsx
  src/presentation/pages/Home/Neoga/style.ts
  src/presentation/pages/Home/Team/index.tsx
Labels: layout 🍃

#300 알림 조회 페이지에 pagination, mutation 적용하기
  src/application/utils/constant.ts
  src/infrastructure/api/team.ts
  src/infrastructure/api/types/team.ts
  src/infrastructure/remote/team.ts
  src/presentation/components/TeamNoticeItem/index.tsx
  src/presentation/pages/Team/Alert/index.tsx
Labels: feature 🎄

#303 팀원 관리 뷰 완성하기!
  src/application/stores/team.ts
  src/infrastructure/api/team.ts
  src/infrastructure/api/types/team.ts
  src/infrastructure/mock/team.ts
  src/infrastructure/remote/team.ts
  src/presentation/components/SearchedUser/ForTeamRegister/index.tsx
  src/presentation/components/SearchedUser/ForTeamRegister/style.ts
  src/presentation/components/SearchedUserItem/index.tsx
  src/presentation/components/SearchedUserItem/style.ts
  src/presentation/components/TeamMemberAdd/ForEdit/index.tsx
  src/presentation/components/TeamMemberAdd/ForEdit/style.ts
  src/presentation/components/TeamMemberAdd/ForRegister/index.tsx
  src/presentation/components/TeamMemberAdd/ForRegister/style.ts
  src/presentation/components/UserSearch/ForTeamRegister/Result/index.tsx
  src/presentation/components/UserSearchResult/index.tsx
  src/presentation/components/UserSearchResult/style.ts
  src/presentation/pages/Team/MemberManagement/index.tsx
  src/presentation/pages/Team/Register/index.tsx
Labels: feature 🎄, layout 🍃

#304 키워드 조회 뷰 수정
  src/infrastructure/remote/neoga.ts
  src/infrastructure/remote/user.ts
  src/presentation/components/common/Empty/Keyword/index.tsx
  src/presentation/components/common/Empty/Keyword/style.ts
  src/presentation/components/common/Keyword/Item/index.tsx
  src/presentation/pages/NeososeoForm/style.ts
  src/presentation/pages/Team/Issue/Feedback/index.tsx
  src/presentation/pages/Team/Issue/Keyword/index.tsx
  src/presentation/pages/Team/Issue/Keyword/style.ts
  src/presentation/pages/Team/Issue/index.tsx
Labels: feature 🎄, layout 🍃

#305 팀 나가기 및 팀장 권한 위임 모달 구현
  src/infrastructure/api/team.ts
  src/infrastructure/mock/team.ts
  src/infrastructure/remote/team.ts
  src/presentation/components/common/BottomSheet/TeamMain/index.tsx
  src/presentation/components/common/Modal/HostDelegation/index.tsx
  src/presentation/components/common/Modal/HostDelegation/style.ts
  src/presentation/components/common/Modal/TeamLeave/index.tsx
  src/presentation/components/common/Modal/TeamLeave/style.ts
  src/presentation/components/common/Modal/style.ts
  src/presentation/pages/Team/Main/index.tsx
Labels: feature 🎄, layout 🍃

#312 이슈 수정하기
  src/infrastructure/api/team.ts
  src/infrastructure/mock/team.ts
  src/infrastructure/remote/team.ts
  src/presentation/components/common/BottomSheet/TeamsoseoPicker/index.tsx
  src/presentation/pages/Team/Issue/Edit/index.tsx
  src/presentation/pages/Team/Issue/Edit/style.ts
  src/presentation/pages/Team/Issue/index.tsx
  src/presentation/routes/TeamRouter.tsx
Labels: feature 🎄, layout 🍃

#318 픽 하기 페이지 완성, 프로필 수정 onBlur 처리 추가
  src/infrastructure/api/types/user.ts
  src/infrastructure/api/user.ts
  src/infrastructure/mock/user.data.ts
  src/infrastructure/mock/user.ts
  src/infrastructure/remote/user.ts
  src/presentation/components/JoinForm/index.tsx
  src/presentation/components/MyItem/index.tsx
  src/presentation/components/MyItem/style.ts
  src/presentation/components/MyListSelectable/index.tsx
  src/presentation/components/MySelectableList/index.tsx
  src/presentation/components/common/Input/index.tsx
  src/presentation/components/common/MyItem/style.ts
  src/presentation/components/common/ProfileList/style.ts
  src/presentation/pages/Edit/Profile/index.tsx
  src/presentation/pages/Home/MyPage/NeogaPick/index.tsx
  src/presentation/pages/Home/MyPage/TeamPick/index.tsx
Labels: refactor 🪐, feature 🎄

#325 팀/이슈 수정하기 이미지 삭제 기능 추가 및 자잘한 작업 많이
  src/application/hooks/useImageUpload.ts
  src/infrastructure/api/team.ts
  src/infrastructure/remote/team.ts
  src/presentation/components/common/FileUpload/index.tsx
  src/presentation/pages/Team/Edit/index.tsx
  src/presentation/pages/Team/Issue/Edit/index.tsx
  src/presentation/pages/Team/Issue/Edit/style.ts
Labels: fix ☔️, feature 🎄, layout 🍃, chore 🍣

#326 너가소개서 설문 만들기 부분 디자인 수정사항 다시 반영
  src/infrastructure/mock/neoga.data.ts
  src/infrastructure/remote/neoga.ts
  src/infrastructure/remote/neososeo-form.ts
  src/presentation/components/NeogaMainCard/Item/index.tsx
  src/presentation/components/NeogaMainCard/Item/style.ts
Labels: layout 🍃, chore 🍣

#329 팀 등록하기 후 setQueryData 해주기
  src/infrastructure/api/team.ts
  src/infrastructure/mock/team.ts
  src/infrastructure/remote/team.ts
  src/presentation/pages/Team/Register/index.tsx
Labels: chore 🍣

#328 피드백 수정하기 구현
  src/infrastructure/api/team.ts
  src/infrastructure/api/types/team.ts
  src/infrastructure/mock/team.ts
  src/infrastructure/remote/team.ts
  src/presentation/components/FeedbackCard/Item/index.tsx
  src/presentation/components/FeedbackCard/List/index.tsx
  src/presentation/components/common/BottomSheet/TeamsoseoPicker/index.tsx
  src/presentation/pages/Team/Issue/Feedback/index.tsx
  src/presentation/pages/Team/Issue/Feedback/style.ts
  src/presentation/pages/Team/Issue/index.tsx
  src/presentation/routes/TeamRouter.tsx
Labels: feature 🎄, layout 🍃

#333 환경 설정 뷰 추가
  src/assets/icons/ic_arrow_right_gray_5.svg
  src/assets/icons/index.ts
  src/infrastructure/api/index.ts
  src/infrastructure/api/service-report.ts
  src/infrastructure/api/user.ts
  src/infrastructure/mock/service-report.ts
  src/infrastructure/mock/user.ts
  src/infrastructure/remote/service-report.ts
  src/infrastructure/remote/user.ts
  src/presentation/components/common/Header/index.tsx
  src/presentation/components/common/SelectBox/index.tsx
  src/presentation/components/common/SelectBox/style.ts
  src/presentation/pages/Neoga/FormDetail/index.tsx
  src/presentation/pages/Preferences/Feedback/index.tsx
  src/presentation/pages/Preferences/ServiceCenter/index.tsx
  src/presentation/pages/Preferences/index.tsx
  src/presentation/pages/Preferences/style.ts
  src/presentation/routes/PreferencesRouter.tsx
  src/presentation/routes/Router.tsx
Labels: feature 🎄

#337 QA 전날 버그 픽스
  src/infrastructure/remote/neoga.ts
  src/presentation/pages/Home/Neoga/index.tsx
  src/presentation/pages/Neoga/Create/index.tsx
  src/presentation/pages/Neoga/FormDetail/index.tsx
Labels: fix ☔️

#338 QA브랜치 배포 세팅
  .github/workflows/deploy-feat.yml
Labels: deployment 🐿

#335 팀장 1인팀인데 나가려고 할 시 팀 삭제하기 유도
  src/presentation/components/common/Modal/TeamLeave/index.tsx
Labels: feature 🎄, layout 🍃

#330 에러 처리 안된 부분들 하기, 모달 스타일 버그 고치기
  src/infrastructure/remote/team.ts
  src/presentation/components/common/Modal/TeamLeave/index.tsx
  src/presentation/components/common/Modal/style.ts
  src/presentation/components/common/ModalWrapper/index.tsx
  src/presentation/components/common/ModalWrapper/style.ts
Labels: fix ☔️, layout 🍃, chore 🍣

#343 엔드포인트 경로 바꾸고 자잘한 수정
  src/infrastructure/api/neoga.ts
  src/infrastructure/mock/neoga.ts
  src/infrastructure/remote/neoga.ts
  src/presentation/components/common/BottomSheet/MyPageEdit/index.tsx
  src/presentation/pages/Neoga/Result/index.tsx
Labels: chore 🍣

#341 5/24 QA
  src/infrastructure/api/user.ts
  src/infrastructure/mock/user.ts
  src/infrastructure/remote/user.ts
  src/presentation/components/JoinForm/index.tsx
  src/presentation/components/NeogaCreateCard/Item/style.ts
  src/presentation/components/TeamNoticeItem/index.tsx
  src/presentation/components/common/BottomSheet/NeososeoPicker/index.tsx
  src/presentation/components/common/BottomSheet/TeamsoseoPicker/index.tsx
  src/presentation/components/common/HomeHeader/style.ts
  src/presentation/pages/Edit/Profile/index.tsx
  src/presentation/pages/Home/MyPage/style.ts
  src/presentation/pages/Neoga/Result/index.tsx
  src/presentation/pages/Neoga/Result/style.ts
Labels: fix ☔️

#334 ImageUpload 컴포넌트 만들기
  src/application/hooks/useImageUpload.ts
  src/assets/icons/index.ts
  src/infrastructure/api/team.ts
  src/infrastructure/api/types/team.ts
  src/infrastructure/remote/team.ts
  src/presentation/components/common/ImageUpload/index.tsx
  src/presentation/components/common/ImageUpload/style.ts
  src/presentation/pages/Preferences/ServiceCenter/index.tsx
  src/presentation/pages/Team/Edit/index.tsx
  src/presentation/pages/Team/Edit/style.ts
  src/presentation/pages/Team/Issue/Edit/index.tsx
  src/presentation/pages/Team/Issue/Edit/style.ts
Labels: feature 🎄

#346 5/26 QA 반영
  src/application/hooks/useLoginUser.ts
  src/presentation/components/FeedbackCard/Item/index.tsx
  src/presentation/components/NeososeoAnswerCard/Item/index.tsx
  src/presentation/pages/Home/MyPage/index.tsx
  src/presentation/pages/NeososeoForm/style.ts
  src/presentation/pages/Team/Issue/Feedback/style.ts
  src/presentation/pages/Team/Issue/NewIssue/style.ts
  src/presentation/style/common/input.ts
Labels: fix ☔️, layout 🍃, chore 🍣

#347 5/26 QA 반영
  src/assets/images/index.ts
  src/presentation/components/NeogaCreateCard/Item/style.ts
  src/presentation/components/common/Empty/Feedback/index.tsx
  src/presentation/components/common/Empty/Feedback/style.ts
  src/presentation/components/common/FileUpload/index.tsx
  src/presentation/pages/Edit/Profile/index.tsx
  src/presentation/pages/Edit/Profile/style.ts
  src/presentation/pages/Neoga/Create/index.tsx
  src/presentation/pages/Neoga/Create/style.ts
  src/presentation/pages/Team/Main/index.tsx
Labels: chore 🍣

#349 5/28 QA 반영
  src/infrastructure/remote/user.ts
  src/presentation/components/TeamNoticeItem/style.ts
  src/presentation/components/common/BottomSheet/MyPageEdit/index.tsx
  src/presentation/components/common/NeogaResultComment/style.ts
  src/presentation/components/common/ProfileItem/style.ts
  src/presentation/pages/Home/MyPage/NeogaPick/index.tsx
  src/presentation/pages/Home/MyPage/TeamPick/index.tsx
  src/presentation/pages/Home/MyPage/style.ts
  src/presentation/pages/Home/Team/style.ts
  src/presentation/pages/MyProfileEdit/index.tsx
  src/presentation/pages/MyProfileEdit/style.ts
  src/presentation/pages/Team/Issue/NewIssue/index.tsx
  src/presentation/pages/Team/Issue/NewIssue/style.ts
  src/presentation/routes/MyPageEditRouter.tsx
Labels: fix ☔️, chore 🍣
