Repository Neogasogaeseo/Naega-Web, pull requests merged in 2022-03, with the labels that each got.

#206 서버 response 바뀌는 부분 똑같이 수정
  src/infrastructure/remote/team.ts
Labels: chore 🍣

#208 📝chore: 서버 response 바뀌는 부분 똑같이 수정
  src/infrastructure/remote/base.ts
  src/infrastructure/remote/user.ts
Labels: refactor 🪐

#204 팀원 등록 페이지를 팀 등록 페이지와 한 페이지가 되도록 리팩토링
  src/application/stores/team.ts
  src/presentation/components/TeamMembers/index.tsx
  src/presentation/components/TeamMembers/style.ts
  src/presentation/components/TeamMembersSearchBar/index.tsx
  src/presentation/pages/Home/Team/index.tsx
  src/presentation/pages/Team/Register/index.tsx
  src/presentation/pages/Team/Register/style.ts
  src/presentation/routes/TeamRouter.tsx
Labels: refactor 🪐

#209 키워드 페이지네이션 구현
  package.json
  src/application/hooks/useScrollHeight.ts
  src/application/utils/constant.ts
  src/infrastructure/api/user.ts
  src/infrastructure/remote/user.ts
  src/presentation/components/common/Loader/index.tsx
  src/presentation/components/common/Loader/style.ts
  src/presentation/pages/Team/Issue/Keyword/index.tsx
  yarn.lock
Labels: feature 🎄

#213 팀원소개서 팀원 목록
  src/application/utils/constant.ts
  src/assets/images/img_empty_main.svg
  src/assets/images/index.ts
  src/infrastructure/api/types/team.ts
  src/infrastructure/mock/team.data.ts
  src/infrastructure/remote/team.ts
  src/presentation/components/common/Empty/HomeNeoga/index.tsx
  src/presentation/components/common/Empty/HomeNeoga/style.ts
  src/presentation/components/common/Empty/HomeTeam/index.tsx
  src/presentation/components/common/Empty/HomeTeam/style.ts
  src/presentation/components/common/IssueTeamInfo/style.ts
  src/presentation/components/common/NeogaResultCard/style.ts
  src/presentation/pages/Team/Main/MemberPopup/index.tsx
  src/presentation/pages/Team/Main/MemberPopup/style.ts
  src/presentation/pages/Team/Main/index.tsx
  src/presentation/pages/Team/Main/style.ts
  src/presentation/pages/Team/Member/index.tsx
  src/presentation/pages/Team/Member/style.ts
  src/presentation/routes/TeamRouter.tsx
  src/presentation/style/common/color.ts
  src/presentation/style/common/font-style.ts
Labels: feature 🎄, layout 🍃

#216 회원가입 페이지 리팩토링, 오류 수정
  src/presentation/components/JoinForm/index.tsx
  src/presentation/components/JoinForm/style.ts
  src/presentation/components/common/CommonInput/index.tsx
  src/presentation/pages/Home/Neoga/index.tsx
  src/presentation/pages/Home/Neoga/style.ts
  src/presentation/pages/Team/Main/index.tsx
Labels: fix ☔️, refactor 🪐

#226 너가소개서 질문 카드 공통 컴포넌트 만들기
  src/assets/icons/ic_link_coral.svg
  src/assets/icons/index.ts
  src/presentation/components/common/QuestionCard/index.tsx
  src/presentation/components/common/QuestionCard/style.ts
  src/presentation/pages/Neoga/Link/index.tsx
  src/presentation/pages/Neoga/Link/style.ts
  src/presentation/style/common/color.ts
Labels: layout 🍃

#231 피드백 작성 뷰 UI 오류 수정
  src/presentation/pages/Team/Issue/Feedback/style.ts
Labels: fix ☔️, layout 🍃

#232 너소서 설문 전체 조회 디자인 반영 및 리팩토링
  src/presentation/components/NeogaCreateCard/Item/index.tsx
  src/presentation/components/NeogaCreateCard/Item/style.ts
  src/presentation/components/NeogaCreateCard/List/index.tsx
  src/presentation/components/NeogaCreateCard/List/style.ts
  src/presentation/pages/Neoga/Create/index.tsx
  src/presentation/pages/Neoga/Create/style.ts
Labels: layout 🍃

#230 베이스 바텀 시트 만들고 너소서 픽/삭제에 예시 만들기
  src/application/hooks/useToast.ts
  src/assets/icons/ic_meatball.svg
  src/assets/icons/ic_pick.svg
  src/assets/icons/ic_trash.svg
  src/assets/icons/index.ts
  src/infrastructure/api/neoga.ts
  src/infrastructure/mock/neoga.ts
  src/infrastructure/remote/neoga.ts
  src/presentation/components/NeogaDetailFormCard/index.tsx
  src/presentation/components/common/BottomSheet/NeososeoPicker/index.tsx
  src/presentation/components/common/BottomSheet/index.tsx
  src/presentation/components/common/BottomSheet/style.ts
  src/presentation/components/common/Toast/Item/index.tsx
  src/presentation/pages/Neoga/FormDetail/index.tsx
  src/presentation/style/common/animation.ts
Labels: feature 🎄

#235 공통 상단 네비게이션 만들기
  src/assets/icons/ic_back.svg
  src/assets/icons/index.ts
  src/presentation/components/common/CommonNavigation/index.tsx
  src/presentation/components/common/CommonNavigation/style.ts
  src/presentation/pages/Team/Register/index.tsx
  src/presentation/pages/Team/Register/style.ts
Labels: feature 🎄, layout 🍃

#234 공통 헤더 만들기
  src/assets/icons/ic_bell.svg
  src/assets/icons/ic_setting.svg
  src/assets/icons/index.ts
  src/assets/images/img_logo.svg
  src/assets/images/img_logo_header.svg
  src/assets/images/index.ts
  src/infrastructure/api/header.ts
  src/infrastructure/api/index.ts
  src/infrastructure/mock/header.ts
  src/presentation/components/common/CommonHeader/index.tsx
  src/presentation/components/common/CommonHeader/style.ts
  src/presentation/pages/Neoga/Link/index.tsx
  src/presentation/pages/Neoga/Link/style.ts
Labels: feature 🎄, layout 🍃

#237 링크 생성 뷰 디자인 수정 사항 반영
  src/assets/icons/ic_link_white.svg
  src/assets/icons/index.ts
  src/assets/images/img_link_created.svg
  src/assets/images/index.ts
  src/infrastructure/remote/neoga.ts
  src/presentation/components/common/FormCard/index.tsx
  src/presentation/components/common/FormCard/style.ts
  src/presentation/components/common/QuestionCard/index.tsx
  src/presentation/pages/Home/Neoga/index.tsx
  src/presentation/pages/Neoga/Create/index.tsx
  src/presentation/pages/Neoga/Link/Result/index.tsx
  src/presentation/pages/Neoga/Link/Result/style.ts
  src/presentation/pages/Neoga/Link/index.tsx
  src/presentation/pages/Neoga/Link/style.ts
  src/presentation/routes/NeogaRouter.tsx
Labels: feature 🎄, layout 🍃

#244 팀원소개서 상세 페이지 수정
  src/infrastructure/api/types/team.ts
  src/infrastructure/mock/team.data.ts
  src/infrastructure/remote/team.ts
  src/presentation/components/common/CommonHeader/style.ts
  src/presentation/components/common/HomeHeader/index.tsx
  src/presentation/pages/Home/Team/index.tsx
  src/presentation/pages/Team/Main/MemberPopup/style.ts
  src/presentation/pages/Team/Main/index.tsx
  src/presentation/pages/Team/Main/style.ts
Labels: refactor 🪐, chore 🍣

#236 팀원소개서 메인 페이지 초대 관련 기획 수정
  src/infrastructure/api/team.ts
  src/infrastructure/mock/team.ts
  src/infrastructure/remote/team.ts
  src/presentation/pages/Home/Team/Invitation/index.tsx
  src/presentation/pages/Home/Team/Invitation/style.ts
  src/presentation/pages/Team/Main/style.ts
Labels: refactor 🪐, chore 🍣

#250 키워드 생성 두 번 눌리는 오류 없애기
  src/presentation/components/common/CommonInput/index.tsx
  src/presentation/pages/Team/Issue/Feedback/index.tsx
  src/presentation/pages/Team/Issue/Keyword/index.tsx
Labels: fix ☔️

#252 common 폴더 내 컴포넌트들 중 Common~으로 시작하는 컴포넌트 폴더명 바꾸기
  src/presentation/components/JoinForm/index.tsx
  src/presentation/components/TeamMembersSearchBar/index.tsx
  src/presentation/components/common/Header/index.tsx
  src/presentation/components/common/Header/style.ts
  src/presentation/components/common/HomeHeader/index.tsx
  src/presentation/components/common/Input/index.tsx
  src/presentation/components/common/Input/style.ts
  src/presentation/components/common/Label/index.tsx
  src/presentation/components/common/Label/style.ts
  src/presentation/components/common/Navigation/index.tsx
  src/presentation/components/common/Navigation/style.ts
  src/presentation/pages/NeososeoForm/Answer/index.tsx
  src/presentation/pages/NeososeoForm/Home/index.tsx
  src/presentation/pages/NeososeoForm/Intro/index.tsx
  src/presentation/pages/Team/Edit/index.tsx
  src/presentation/pages/Team/Issue/Feedback/index.tsx
  src/presentation/pages/Team/Issue/Keyword/index.tsx
  src/presentation/pages/Team/Issue/index.tsx
  src/presentation/pages/Team/Main/index.tsx
  src/presentation/pages/Team/Register/index.tsx
Labels: chore 🍣
